### ISSUE TITLE
Option to specify `sourcefile` in download configuration for a project

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystmd#1065]
### Context

The `download:` configuration currently expects you to specify a path or an ID to a specific download object.

However, for project-wide configuration, there's no way to specify "Add a download link to the source file". This is a common pattern that is currently over-ridden if you specify any project-wide download configuration.

### Proposal

Make it possible to add a sourcefile placeholder in the download config.

For example:

```yaml
download:
  - file: somefile.pdf
  # If we use an ID for this
  - id: _sourcefile
  # If we use a key for this
  - sourcefile: true
```
