### ISSUE TITLE
Tex exports with local templates and without explicit format fail

### ISSUE THREAD

**Issue by fwkoch** [executablebooks/mystmd#1084]
## Description

With frontmatter:

```yaml
exports:
  - output: out.tex
    template: ../my-template-tex
```

calling

```bash
myst build --tex
```

results in no exports. This is an edge case in the format resolution function, where pdf format from template overrides `.tex` output extension: https://github.com/executablebooks/mystmd/blob/main/packages/myst-cli/src/build/utils/collectExportOptions.ts#L138

## Proposed solution

Just a small tweak to the code linked above so output extension is still respected in the local template case.
