### ISSUE TITLE
Locating jupyter servers for executing notebooks during build - Docker

### ISSUE THREAD

**Issue by agahkarakuzu** [executablebooks/mystmd#1224]
Hi! 

As noted in the documentation, the detection of the Jupyter Server for executing notebooks during a build is based solely on:

https://github.com/executablebooks/mystmd/blob/501e64a01da9a7ccde8b2f692005263c733e02f2/packages/myst-execute/src/manager.ts#L33

However, even when a server is exposed to the `localhost` from a container and described in the `myst.yaml` as follows

```yaml
  jupyter:
    server:
      url: http://localhost:8888
      token: 3c7ee818e7a2543c248d75e08c1fbdfe0f464b39
```

the `myst build --execute` command will ignore it since the Jupyter Hub is not considered "local" as defined by the `jupyter server list`.

## Proposal

Would it be possible to first check, e.g., `http://localhost:8888/api/status?token=3c7ee818e7a2543c248d75e08c1fbdfe0f464b39` for `200` (or another [endpoint](https://jupyter-server.readthedocs.io/en/latest/developers/rest-api.html) of your choice) before proceeding with the default method?

## Additional notes

I am unsure if exposing a Jupyter server to `localhost:port` through a container is a viable option as locally spawn servers are using web sockets, not tcp. 

If there is an alternative way to make this work, I am happy to use that solution instead of requesting an enhancement.

Thank you for maintaining this amazing project!

**Comment by agoose77** [comment]
@agahkarakuzu I think once you are involving a container to run a server, it's sufficiently "power-user" that the manual mechanism of specifying the server details is an acceptable UX:

https://mystmd.org/guide/execute-notebooks#manually-launch-a-jupyter-server

You can set both `JUPYTER_BASE_URL` and `JUYPTER_TOKEN` to instruct MyST to connect to the server!

**Comment by agoose77** [comment]
Also, the fact that the MyST config is ignored:
```yaml
  jupyter:
    server:
      url: http://localhost:8888
      token: 3c7ee818e7a2543c248d75e08c1fbdfe0f464b39
```
Is a feature request/bug: #1214
