### ISSUE TITLE
Automatic table numbering

### ISSUE THREAD

**Issue by roaldarbol** [executablebooks/mystmd#1241]
Currently it seems that tables aren't automatically numbered. I've found examples where numbering is specified in `myst.toml`:
```
# See docs at: https://mystmd.org/guide/frontmatter
version: 1
project:
  ...
  numbering:
    table: true
```

## Proposal
Like figures, having table numbering would be great!
