### ISSUE TITLE
Improvements to support `parts` for exports

### ISSUE THREAD

**Issue by fwkoch** [executablebooks/mystmd#1246]
Individual files allow `parts` to be defined in their frontmatter. These are respected for static exports of those files. However, parts cannot be defined at the project/export level. We should extend the frontmatter `parts` to be allowed there:

```yaml
...
project:
  exports:
    - format: pdf
      abstract: My Custom Export Abstract
```

Additionally, it would be nice to allow these to be paths to files rather than inline text.
