### ISSUE TITLE
Export to docx works, pdf does not

### ISSUE THREAD

**Issue by VRConservation** [executablebooks/mystmd#1303]
## Version/OS
myst v1.2.7, OS ubuntu

## Description
When I run `myst build my-document.md` a version of the md file is converted to word but not to pdf. Here's the front matter in the md file (I've excluded all the other front matter from title to abstract)
```
exports:
  - format: docx
  - format: pdf
    template: volcanic
    article_type: report
```

## Additional notes
Here's the error in the terminal:

![image](https://github.com/executablebooks/mystmd/assets/61313347/9f46c78e-2292-4f91-95d0-cb96da043fad)

Thanks for any help.
