### ISSUE TITLE
Flatten `myst.yml`

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystmd#1308]
Right now we have a few high level keys in the `myst.yml` including project/site/version/extends. It is confusing to users where to put the keys (mostly always under project). Additionally, when writing a shared configuration, for example, abbreviations, authors, etc. that requires you to write it under the project key.

Instead, I suggest that we lean into the single project, and flatten all keys that are in the project. Moving from:

```yaml
version: 1
project:
  open_access: true
  license:
    content: Apache-2.0
    code: CC-BY-4.0
  references:
    foundations: https://projectpythia-mystmd.github.io/pythia-foundations
site:
  template: book-theme
```

to

```yaml
version: 1
open_access: true
license:
  content: Apache-2.0
  code: CC-BY-4.0
references:
  foundations: https://projectpythia-mystmd.github.io/pythia-foundations
site:
  template: book-theme
```

There are still potentially some site options to configure, but they will be obviously related to the theme (nav links, footer, etc.).

@jmunroe
