### ISSUE TITLE
`myst init` should populate a `toc` placeholder entry

### ISSUE THREAD

**Issue by agoose77** [executablebooks/mystmd#1310]
See title!

**Comment by rowanc1** [comment]
I have updated this to have the default be:

```yaml
# See docs at: https://mystmd.org/guide/frontmatter
version: 1
project:
  id: b74033ac-0de7-44d2-81e6-e1d534d7769f
  # title:
  # description:
  # keywords: []
  # authors: []
  github: https://github.com/executablebooks/mystmd
  # To autogenerate a Table of Contents, run "myst init --write-toc"
site:
  template: book-theme
  # options:
  #   favicon: favicon.ico
  #   logo: site_logo.png
```

Thoughts?
