### ISSUE TITLE
Table of content, patterns and nested directories

### ISSUE THREAD

**Issue by nthiery** [executablebooks/mystmd#1323]
Provide a way to control the hierarchy in the table of contents when using patterns, in particular to enable compatibility with JupyterBook.

## The problem

Let's consider some deep hierarchy of documents
```
- A1/
   - A11/
       - A111.md
       - A112.md
- A2
    - A21/
        - ...
``` 

**Use case 1:** you want to build automatically the whole table of content, with the hierarchy of directories being reflected in a hierarchy in the toc. In that case, you expect:
```
toc:
   - pattern: */*/*.md
```
to result in a nested table of content such as:
```
> A1
    > A11
          A111.md
          A112.md
> A2
        ...
```
That's what MyST does.

**Use case 2:** you want to control the nesting of your table of content. E.g. because you want to choose your own titles for the directories. Or maybe have a nesting that is different from the directory hierarchy. So you expect the following configuration:
```
toc:
   - title: The introduction
     content:
      - title: bar
        content:
          - pattern: A1/A11/*.md
   - title: User guide
     ...
``` 
to produce:
```
> The Introduction
  > Bar
        A111.md
        A112.md
> User Guide
            ...
```

However, with the current MyST and unlike JupyterBook, the produced TOC is doubly nested:
```
> The Introduction
  > Bar
     > A1
        > A11
              A111.md
              A112.md
> User Guide
            ...
```

## Proposal

I am not sure whether this should be qualified as a bug: automatic building the hierarchy in the toc can be useful as in Use Case 1. However we would need to support Use Case 2 as well, in particular for migrating from the current JupyterBook to MyST. Somehow, we would want the hierarchy to be built relatively to the current toc section, but I feel like matching a subdirectory with a toc folder is not necessarily 1 to 1, especially when having sections defined by just a title, not a file. Maybe we could have something like:
```
...
   - pattern: */*/*.md
```
would produces a flat table of content (as in JB), while:
```
...
   - pattern:
        - glob: foo/*/*.md
        - root: foo/ 
```
would produce a nested table of content w.r.t. the given root ???

## Additional notes

Thank you so much for the new `toc` syntax in MyST. It's one more step in the migration, and it so much systematic than the `toc` syntax in the current JB.

@choldgraf : you may want to mention this issue in the tracking issue for the JB->MyST migration.

**Comment by agoose77** [comment]
@rowanc1 @fwkoch my feeling here is that patterns should _always_ be flat. I think there's value in having the TOC be an explicit source of truth for structure, i.e.

<table>
<tr>
<td> TOC </td> <td> Expanded TOC </td>
</tr>

<tr>
<td>

```yaml
toc:
  - file: foo.md
  - title: Children
    pattern: bar/baz/*.md
```

</td>
<td>

```yaml
toc:
  - file: foo.md
  - title: Children
    children: 
      - file: bar/baz/a.md
      - file: bar/baz/b.md
```

</td>
</tr>

</table>

Any thoughts?

**Comment by fwkoch** [comment]
Hmm, yeah - I did change the implementation from "always flat" to "follow MyST's implicit toc structure" for patterns.

My primary motivation was around the non-deterministic ordering of the flat files. They were just using the underlying system ordering (e.g. ordered by date modified or something). This felt a little bad.

My secondary motivation was, well... lack of familiarity with JB and intimate familiarity with MyST. So, to me, following the other implicit toc resolution made sense.

I totally understand the reasoning around flat pattern expansion, especially after reading through @nthiery's examples - though I do agree, there is _maybe_ still a use case for the implicit structure I implemented.

---

Maybe the next steps here are:

1. Re-implement flat expansion, but add deterministic ordering, e.g. `index` first, then alphabetic, etc. Maybe this even uses the existing implicit toc structure without the folder nesting?
2. Possibly add an option to keep the folder structure, something like this:
  ```yaml
  ...
  - pattern: */*/*.md
    folders: true
  ```
  and maybe even have the `root` option, like @nthiery mentioned...?

**Comment by agoose77** [comment]
@fwkoch I like your suggestions. It's my feeling that there's value in the TOC being as deterministic as possible, i.e. to capture as much of the detail about the project as possible. Moreover, declaring the full structure gives us a lot more control over things like folder titles, etc.

So, my suggestion is that we use the implicit TOC resolution logic, but flatten it to a list of leaf nodes.

**Comment by dcamron** [comment]
Related, on myst v1.2.9, given my existing Jupyter Book `_toc.yml` with `parts > chapters > sections > glob` entries (can provide if needed), `myst init --write-toc` did not convert my existing patterns to the newly generated TOC config.

**Comment by mfisher87** [comment]
I'm not sure how I feel about @fwkoch 's proposal above. What I personally am usually looking for is to have dynamic TOC generation, i.e. the behavior when no `toc` is provided (plus #2799), for a subtree of my toc, and I see that as separate from and combinable with pattern matching (and, IMO, pattern-matching comes with an accessibility cost). I also find the use of `folders` confusing because right now that relates to slug-generation not TOC. Maybe something like this?

```yaml
  toc:
    - file: "index.md"
    - url: "https://example.com"
    - title: "Our practices"
      dynamic: "practices/"
```

and also supported:

```yaml
  toc:
    - file: "index.md"
    - url: "https://example.com"
    - title: "Our practices"
      pattern: "practices/**/practice-*.md"
      dynamic: true
```


EDIT: I misunderstood `folders: true`. The default behavior when a `toc` is not provided is to generate it, and I always had `folders: true` on for the slug-generation behavior and thought it caused both the slug-generation behavior and toc-generation 🙃 Changed the comment to reflect my new learning.
