### ISSUE TITLE
index.html is not generated in static HTML builds when in a nested folder

### ISSUE THREAD

**Issue by vangeest** [executablebooks/mystmd#2001]
## Description
When index.md is present, an index.html file is not created in some cases.

I only see the problem with index.md, I do not encounter it with any other files like root.md or README.md.

I cannot exactly pinpoint in which configurations this happens and in which is doesn't, but I have isolated one example in which the index.md consitently is not created. 

## Example where index.html is not created

In this exampe root.html and readme.html are generated based on root.md and README.md. 
index.html is not generated, eventhough index.md is present

Information on this example:

Relevant piece from mist.yml
```
 toc:
    - file: README.md
    - file: 1-game/index.md
      children:
        - pattern: 1-game/*-*.md
    - file: 2-webshop/root.md
      children:
        - pattern: 2-webshop/*-*.md
```

It seems that for reproduction, it is relevant that a static site is build with
`myst build --html`

and it may be relevant for reproduction that `myst.yml` contains 
```
site:
  template: book-theme
  options:
    folders: true  
```
Link to complete example which demonstrates this issue
https://github.com/informaticascw/informaticascw.github.io/tree/e92a8062ec8f31d527304eb59221faaa3c56f8fd

Using myst v1.3.36

Using `npx -y http-server _build/html -c-1 &` for static serving in my development environtment which I used to reproduce this (allthough this does not seem relevant).

## Proposed solution
always generate index.html when index.md is present, 

This seems to be the expected behaviour when I read
https://mystmd.org/guide/table-of-contents#root-page

## Additional notes
none

**Comment by FreekPols** [comment]
Isnt it the hierarchy.. your readme.md file is on top, your index.md is in a folder...

**Comment by vangeest** [comment]
I tested with index.md in the root and indeed, in that case https://domain/ returns the home page.

There is still something strange when the index.md is in the root though:
https://domain/index.html returns

```
TypeError: Cannot read properties of undefined (reading 'handle')
    at https://organic-engine-vq7q59wgrpx3wgw5-8080.app.github.dev/build/_shared/chunk-OCTKKCIL.js:26:2273
    at Array.map (<anonymous>)
    at https://organic-engine-vq7q59wgrpx3wgw5-8080.app.github.dev/build/_shared/chunk-OCTKKCIL.js:26:2193
    at Object.useMemo (https://organic-engine-vq7q59wgrpx3wgw5-8080.app.github.dev/build/_shared/chunk-UAI5KRM7.js:6:23210)
    at N.useMemo (https://organic-engine-vq7q59wgrpx3wgw5-8080.app.github.dev/build/_shared/chunk-UAI5KRM7.js:1:6271)
    at br (https://organic-engine-vq7q59wgrpx3wgw5-8080.app.github.dev/build/_shared/chunk-OCTKKCIL.js:26:2179)
    at mi (https://organic-engine-vq7q59wgrpx3wgw5-8080.app.github.dev/build/_shared/chunk-OCTKKCIL.js:32:3943)
    at Po (https://organic-engine-vq7q59wgrpx3wgw5-8080.app.github.dev/build/_shared/chunk-UAI5KRM7.js:6:16957)
    at pc (https://organic-engine-vq7q59wgrpx3wgw5-8080.app.github.dev/build/_shared/chunk-UAI5KRM7.js:8:43666)
    at cc (https://organic-engine-vq7q59wgrpx3wgw5-8080.app.github.dev/build/_shared/chunk-UAI5KRM7.js:8:39465)
```

I have no clue what this means (lack of knowledge on this subject from my side), but I would expect the home page to be shown.

relevant part of my myst.md used for this test:
```
toc:
    - file: index.md
    - file: 1-game/README.md
      children:
        - pattern: 1-game/*-*.md
    - file: 2-webshop/root.md
      children:
        - pattern: 2-webshop/*-*.md
```
