### ISSUE TITLE
Overhaul template handling

### ISSUE THREAD

**Issue by agoose77** [executablebooks/mystmd#2041]
There are presently a few pain points / areas of confusion with templates:

- #2031 
- #2032 
- #131
- #2033

This initiative tracks some possible high-level improvements.

Following recent conversations around templates, we've been discussing (on Discord) moving away from an API server towards bring-your-own-template (closing #131). This would reduce the maintenance burden for us, and the confusion for users around the nuances of this system.

If we removed the template API server, we would benefit from a nicer way to specify a template than a full URL. @choldgraf suggested the Binder API URL scheme:

- `gh/ORG/REPO`
- `gl/ORG/REPO`
- `gist/ID`

We could extend the configuration that we understand to support this, and a verbose style e.g.:

```yaml
site:
  template: gh/myst-templates/book-theme
```
is identical to 

```yaml
site:
  template: 
    github: myst-templates/book-theme
```

And finally, we could add support for template sub-paths:

```yaml
site:
  template: 
    github: myst-templates/book-theme
    path: ./path/to/book/template/in/repo
```
