### ISSUE TITLE
Frontmatter social/email icons not consistently appearing in authors field

### ISSUE THREAD

**Issue by ktyle** [executablebooks/mystmd#2109]
## Description

When building a [mystmd project site](https://www.atmos.albany.edu/facstaff/ktyle/atm350_2026/), (mystmd version: 1.4.0) I've noticed a couple of misbehaviors when adding sections to the `authors` field:

1. `bluesky` icon/link does not appear 
2. The `email` icon/link does not appear for the second author

## Additional notes

The relevant part of the `myst.yml` file appears below (full project's GitHub source is [here](https://github.com/ktyle/350_2026_book)):

```
project:
  id: 08f555cb-793d-4ea9-874c-350b9de88eb0
  title: ATM350 Spring 2026
  description: Course website for ATM350, Spring 2026
  authors:
    - name: Kevin Tyle
      affiliations:
        - University at Albany
        - Project Pythia
      orcid: 0000-0001-5249-9665
      email: ktyle@albany.edu
      twitter: nywxguy
      bluesky: https://bsky.app/profile/nywxguy.bsky.social
    - name: Ross Lazear
      affiliations:
      - University at Albany
      orcid: 0009-0006-6195-6868
      email: rlazear@albany.edu
```

**Comment by rowanc1** [comment]
You can add `corresponding: true` to anyone that you want the email icon to appear. By default it is the first author with an email if not specified. We only show one email address in the icons at the moment, although each is show in the author details on click.

Bluesky icon is working it's way through - requires consuming some updates in the theme!

**Comment by ktyle** [comment]
@rowanc1 thanks! I just added `corresponding: true` to the 2nd author but still not seeing the email icon appear for him.

**Comment by rowanc1** [comment]
Do they have an email as well? It works in my testing now of the article-theme and looking at the [code](https://github.com/jupyter-book/myst-theme/blob/main/packages/frontmatter/src/Authors.tsx#L44) it should work..!

![Image](https://github.com/user-attachments/assets/b4e47730-7300-40e8-bcab-093b7ceb0e7f)

**Comment by ktyle** [comment]
Yep, and I also just tried replacing `authors:` with `contributors:` following your screenshot above. Below is my full `myst.yaml`:

```
# See docs at: https://mystmd.org/guide/frontmatter
version: 1
project:
  id: 08f555cb-793d-4ea9-874c-350b9de88eb0
  title: ATM350 Spring 2026
  description: Course website for ATM350, Spring 2026
  contributors:
    - id: ktyle
      name: Kevin Tyle
      affiliations:
        - University at Albany
        - Project Pythia
      orcid: 0000-0001-5249-9665
      email: ktyle@albany.edu
      twitter: nywxguy
      bluesky: https://bsky.app/profile/nywxguy.bsky.social
    - id: rlazear
      name: Ross Lazear
      affiliations:
        - University at Albany
      corresponding: true
      orcid: 0009-0006-6195-6868
      email: rlazear@albany.edu
  license: CC-BY-4.0

  keywords: ["python", "meteorology"]
  #
  # github:
  # To autogenerate a Table of Contents, run "myst init --write-toc"
  toc:
    # Auto-generated by `myst init --write-toc`
    - file: index.md
    - file: test.md
    - file: sample.ipynb
    - file: datetime.ipynb

site:
  template: book-theme
  # options:
  #   favicon: favicon.ico
  #   logo: site_logo.png
```

**Comment by rowanc1** [comment]
You will need the `corresponding` on **both** you and Ross. Here I would only expect the icon on Ross. I would recommend authors generally. Only had contributors in mine so that I could make the author list by a number of `- id: rowan` etc. as it was long and hard to reorder to alphabetical!

```yaml
# See docs at: https://mystmd.org/guide/frontmatter
version: 1
project:
  id: 08f555cb-793d-4ea9-874c-350b9de88eb0
  title: ATM350 Spring 2026
  description: Course website for ATM350, Spring 2026
  authors:
    - id: ktyle
      name: Kevin Tyle
      affiliations:
        - University at Albany
        - Project Pythia
      orcid: 0000-0001-5249-9665
      email: ktyle@albany.edu
      corresponding: true
      twitter: nywxguy
      bluesky: https://bsky.app/profile/nywxguy.bsky.social
    - id: rlazear
      name: Ross Lazear
      affiliations:
        - University at Albany
      orcid: 0009-0006-6195-6868
      email: rlazear@albany.edu
      corresponding: true
  license: CC-BY-4.0
```
