### ISSUE TITLE
Combine multiple articles/notebooks into a single pdf

### ISSUE THREAD

**Issue by fcarvalhopacheco** [executablebooks/mystmd#436]
## Description

I am trying to create a project that has the following initial structure:

```bash
1.abstract.md
2.testing.ipynb
myst.yml
_toc.yml
```

How can I generate a pdf or word or jats that includes both ```1.abstract.md``` and ```2.testing.ipynb```? 
Right now ```myst build --pdf``` only render ```1.abstract.md```

My ```2.testing.ipynb``` file has the following frontmatter:

```
---
title: whaterver
subtitle: ............
exports:
  - format: pdf
    template: plain_latex
    output: exports
---

```
