### ISSUE TITLE
PDF images don't convert in GitHub Actions

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystmd#452]
Need to investigate further on this one!

**Comment by Jan-David-Black** [comment]
:+1:

**Comment by Jan-David-Black** [comment]
For reference, this is the error I get:
```
2023-07-31T13:42:43.9808172Z Could not convert from PDF to PNG: _build/site/public/width_sweep-8bca976875a10bf293f360c1ef6fe9c8.pdf - Error: Command failed: convert -density 600 -colorspace RGB _build/site/public/width_sweep-8bca976875a10bf293f360c1ef6fe9c8.pdf _build/site/public/width_sweep-8bca976875a10bf293f360c1ef6fe9c8.png
2023-07-31T13:42:43.9809205Z convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421.
 ```

**Comment by Jan-David-Black** [comment]
Seems to be an issue with imagemagick being very cautious with pdf conversion due to a ghostscript vulnerability: https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion

**Comment by jan-david-fischbach** [comment]
```yaml
- run: sudo apt-get update
- run: sudo apt-get -y install ghostscript
- run: sudo sed -i '/domain="coder" rights="none"/d' /etc/ImageMagick-6/policy.xml
```
This cirvumvents the bug. We should probably also mmake sure to install Ghostscript ≥9.24 to avoid the vulnurability
