### ISSUE TITLE
Adding a capability to remove or hide left, right, and bottom panels

### ISSUE THREAD

**Issue by sgkang** [executablebooks/mystmd#462]
## Proposal

Adding a capability to hide or remove:

- left panel
- right panel
- bottom panel 

<img width="1482" alt="tmp" src="https://github.com/executablebooks/mystmd/assets/6054371/9653b9b4-ff93-4e0b-9505-e39deb3a16c0">

For a very specific reason (running an Jupyter widget through mystmd), I would like to only expose the content of a mystmd page without other information. 
Currently, it is not possible. It would be great if the mystmd team could add this functionality!

**Comment by stevejpurves** [comment]
Thanks @sgkang - I think what you want is probably better served by a different theme rather than, adding options to trim back the `myst-book-theme` which you are currently showing above. That could make other design accomodations specific to you use case too.

**Comment by stevejpurves** [comment]
@sgkang in the current book theme you are using you can add `hide_toc` to get rid of the table of contents (left hand panel). your yaml file woul look like:

```yaml
site:
   template: book-theme
   hide_toc: true
```

Once this PR comes in https://github.com/executablebooks/myst-theme/pull/161 and is released then the article theme might fit your purpose better.

```yaml
site:
   template: book-theme
   hide_toc: true
   hide_footer: true
```

As this removes the on individual pages I'd suggest using your index page to a listing with links links to the rest of your site, for people who land on your site root.

also you can discover which options are available on a template by getting a list of website template names:

```bash
myst templates list ---site
```

and then getting the options by

```bash
myst templates list <template-name>
```

**Comment by stevejpurves** [comment]
@sgkang the `article-theme` was released with these changes already. So you can try:
```
site:
   template: article-theme
   hide_toc: true
   hide_footer: true
```
