### ISSUE TITLE
cli displays errors during `meca` build with glob patterns

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/mystmd#465]
myst v1.1.1

## Description
Running `myst build --meca` with the following project frontmatter:

```
project:
  requirements:
    - environment.yml
  resources:
    - src/**/*
    - model.pickle
  exports:
    - format: meca
```

Results in a meca.zip file that contains all the expected content, but produces `Error copying file: src`, `Error copying file: src/subfolder` errors for each directory in the glob.

## Proposed solution

Probably we need to filter directories out of the file list that we are copying.
