### ISSUE TITLE
Hiding notebooks while keeping linked labels

### ISSUE THREAD

**Issue by kolibril13** [executablebooks/mystmd#466]
Notebooks can currently be hidden in a myst project by not including them in `_toc.yml` ( as mentioned in  https://github.com/executablebooks/mystmd/issues/434).
But when hiding them, all labeled content from notebooks cannot be used.
It would be great if the labeled notebook output with for example `#| label: my-image` could still be used in the myst documents when a notebook is hidden from the toc!

## Motivation

I often quickly draft some code for a visualization that I want to show.
The code does its job, but I normally don't polish it after the visualization looks like I want it to look like.
I don't mind when that code is available on a public GitHub repo, but I don't want to put too much emphasis on that, so it would be amazing if the unpolished backend of the visualization could be hidden in myst.
 
 <img width="172" alt="image" src="https://github.com/executablebooks/mystmd/assets/44469195/63b71631-ff07-42de-a39b-6215dc047bd9">

**Comment by stevejpurves** [comment]
we've been thinking the exact same thing @kolibril13 -- current thoughts are to update the `_toc.yml` to allow you wo specify this. Perhaps something like:

```
format: jb-book
root: paper
chapters:
  - file: appendix.md
  - file: supplementary.ipynb
  - file: behind-the-scenes-1.ipynb
    hidden: true
  - file: behind-the-scenes-2.ipynb
    hidden: true
```

**Comment by kolibril13** [comment]
hi @stevejpurves ,
that's really great to hear!
Here is my alternative `_toc.yml` syntax suggestion:

```
format: jb-book
root: paper
chapters:
  - file: appendix.md
  - file: supplementary.ipynb

hidden-chapters:
  - file: behind-the-scenes-1.ipynb
  - file: behind-the-scenes-2.ipynb
  - file: behind-the-scenes-3.ipynb
  - file: behind-the-scenes-4.ipynb

```
