### ISSUE TITLE
Myst build ignoring nested page trees

### ISSUE THREAD

**Issue by lalligagger** [executablebooks/mystmd#478]
## Description

Using a [test project](https://curvenote.com/@lalli/page-tree-test/) created in Curvenote, myst CLI seems to ignore any hierarchy in page tree.

myst: `v0.1.29`

## Additional notes
I get the slightly different behavior using Curvenote publish vs. local myst build (see screenshot), but neither shows the intended nesting. Opening after a quick chat with @rowanc1 as we both think this worked at some point. :)

<img width="625" alt="image" src="https://github.com/executablebooks/mystmd/assets/11700267/51b9a1f4-5161-46d4-8868-4a760463e238">

**Comment by lalligagger** [comment]
Here are the curvenote.yml & myst.yml that I am seeing:

`myst.yml`:
```
# See docs at: https://myst-tools.org/docs/mystjs/frontmatter
version: 1
project:
  # title:
  # description:
  keywords: []
  authors: []
  # github:
  # bibliography: []
site:
  template: book-theme
  # title:
  # logo:
  projects:
    - slug: myst
      path: .
  nav: []
  actions:
    - title: Learn More
      url: https://myst-tools.org/docs/mystjs
  domains: []
```

`curvenote.yml`:
```
version: 1
site:
  title: opticsinspace
  projects:
    - slug: opticsinspace
      path: ../opticsinspace
    - slug: opticsinspace
      path: ../opticsinspace
    - slug: page-tree-test
      path: content/page-tree-test
  nav:
    - title: opticsinspace
      url: /opticsinspace
    - title: opticsinspace
      url: /opticsinspace
    - title: page-tree-test
      url: /page-tree-test
  actions:
    - title: Learn More
      url: https://docs.curvenote.com/web
  domains:
    - lalli.curve.space
```
curvenote `_toc.yml`:
```
# Table of contents
# Learn more at https://jupyterbook.org/customize/toc.html

format: jb-book
root: root
chapters:
  - file: blank
    sections:
      - file: article-1
  - file: topic-2
    sections:
      - file: article-2
```
