### ISSUE TITLE
Extend authors frontmatter to allow given and family names

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/mystmd#571]
## Proposal
Allow structured objects to be provided as author names, as an alternative to a plain string

When a plain string is provided it will be parsed (using bibtex rules?) into an object in the form of:

```
authors:
  - Lucia de La Cruz
  - given: Luciz
    family: Cruz
    dropping_particle: de
    non_dropping_particle: La
```

(Or something like that ☝🏼 please update the spec here as we learn more)

## Additional notes
- object will pass through to JATS and LaTeX
