### ISSUE TITLE
Problem in PDF rendering

### ISSUE THREAD

**Issue by satishchaudhary382** [executablebooks/mystmd#640]
## Version of Myst used
v1.1.20

## Installation of Myst
npm

## OS used 
Windows

## Description
I was trying to render the markdown into pdf and docx. The markdown gets converted into docx with ease however it gives error while rendering into the pdf format. 

![image](https://github.com/executablebooks/mystmd/assets/39291322/321bd199-93ea-495c-b587-a440f6bc2c74)

## Additional notes
Any help what is going wrong here

**Comment by dressedfez** [comment]
The template you are using needs an abstract part, i.e. something like this in the paper.md

```
+++ {"part": "abstract"}

abstract text here

+++
```

The second error means that you need to provide an authors part in the frontmatter of the paper, i.e. something like this:

```
authors:
  - name: Rowan Cockett
    affiliations:
      - Executable Books
      - Curvenote
    orcid: 0000-0002-7859-8394
    email: rowan@curvenote.com
```

Please have a look at https://mystmd.org/guide/quickstart-myst-documents 

@rowanc1 maybe it would be a good idea to update the webpage in such a way that the initial setup is described in a different way as in the provided link. I personally think that the removing errors approach might not be a good start. It works nicely in your presentation, but if you want to start from scratch without assistance from others than this approach is misleading.
