### ISSUE TITLE
Extend author frontmatter to support "et al." 

### ISSUE THREAD

**Issue by nthiery** [executablebooks/mystmd#642]
Add support in the frontmatter for the traditional "et al." idiom to
specify that many others contributed to the document.

I am currently using:
```
  authors:
    - name: Nicolas M. Thiéry
      ...
    - name: et al.
```

This is presumably mostly a question of standardizing in the documentation how
to handle this case; and maybe a tiny bit of presentation?
