### ISSUE TITLE
Improvements to multi-page PDF exports

### ISSUE THREAD

**Issue by fwkoch** [executablebooks/mystmd#799]
Building a PDF from multiple md files (or chapters) was implemented here: https://github.com/executablebooks/mystmd/pull/772

You may do this by specifying multiple `articles` in your `export` frontmatter, e.g.

```yaml
exports:
  - format: pdf
    articles:
      - 01_introduction.md
      - 02_method.md
      - 03_results.md
      - 04_discussion.md
      - 05_conclusion.md
```

There are still 2 outstanding issues to improve:
- [ ] Add option to use `_toc.yml` for chapters instead of listing them explicitly in the frontmatter
- [ ] Fix bug where the first header of each page is removed - it is being converted to `title` but then lost. (For now, you can get around this bug by defining a `title` in each page's frontmatter.)

**Comment by fwkoch** [comment]
For templated multi-article exports, page frontmatter on each article is ignored; frontmatter must be defined in the `myst.yml` file. This is even the case if the `export` itself is defined on a page instead of `myst.yml`.

If frontmatter is defined in the wrong place, there is no helpful reporting or anything; the template just says it cannot find the relevant fields. I think we should at least pull frontmatter from the page where the export is defined. Then we could also search around the frontmatter for every page and log when things are defined but ignored.

**Comment by quant-dc** [comment]
@fwkoch this is fantastic, thank you so much. It is one of the main features that I was hoping for to move more from Jupyter Book to mystmd. I'm struggling a little bit to understand the setup required when it comes to frontmatter and the `myst.yml` file.

I've been trying to test this out with the simple `mystmd-quickstart` example. I've struggled to get it working with a bit of trial and error, and not been able to find any documentation of this new feature. Is it the case that I need to add the following fields to the `myst.yml` file:

```
project:
  title: Example
  authors:
    - name: John Smith
```

And then create a new file, for example `00-overall.md` which simple contains the following:

```
---
exports:
  - format: pdf
    template: plain_latex_book
    articles:
      - 01-paper.md
      - 02-notebook.ipynb
---
```

At which point I can run:

```shell
myst build 00-overall.md
```

@rowanc1 I believe that this is a template that you created for this work, might you have an example of using it?
