### ISSUE TITLE
Intersphinx scheme diverges from `myst-parser`

### ISSUE THREAD

**Issue by agoose77** [executablebooks/mystmd#851]
## Description

MyST (CLI) uses `myst:` as the scheme for intersphinx references. Meanwhile, `myst-parser` uses `inv:`. On the face of it, I prefer `inv:` because intersphinx is something MyST supports, but is not first-class (i.e. we could do better). I believe @rowanc1 and I discussed this in a recent call.

If we're planning on improving upon intersphinx (let it be known that I don't fully conceive of what we would do here, it's just a possibility), then we might want to reserve `myst:` for this mechanism. 

## Proposed solution

If/when a new MyST alternative to intersphinx is designed, we *don't* want to implicitly switch between the two, e.g. ask for `.json` before `objects.inv`. I suspect that the failure modes of this would be non-obvious; what if the `.json` request fails for some reason, and the build falls back on intersphinx? The user won't see what they expect.

Therefore, I think we have the following sensible options:
1. Explicit intersphinx-like referencing at the scheme level:
   - Deprecate the `myst:` scheme until we've implemented it
   - Add support for the `inv:` scheme
   - Deprecate the `references:` frontmatter key
   - Add new `sphinx-references:` frontmatter key 
     ```yaml
     sphinx-references:
       python: https://docs.python.org/3.7/
       jupyterbook: https://jupyterbook.org/en/stable/
     ```
2. Explicit intersphinx-like referencing at the frontmatter _reference_ level
   - Change `references` items to be objects:
     ```yaml
     references:
       python: 
         url: https://docs.python.org/3.7/
         kind: intersphinx
       jupyterbook: 
         url: https://jupyterbook.org/en/stable/
         kind: intersphinx
     ```

Maybe this is _too_ strict. Pinging @rowanc1 / @stevejpurves / @fwkoch on this.
