### ISSUE TITLE
Clarification on setting a theme. 

### ISSUE THREAD

**Issue by jbusecke** [executablebooks/mystmd#881]
I just set up a vanilla test project by running `myst init` and adding a simple .md file.

```md
---
title: Test?
author: Julius Busecke
---

# Some heading 

Some text
```
in `test.md`

And followed [these](https://mystmd.org/guide/website-themes#changing-themes) instructions to change the theme

```yaml
version: 1
project:
  keywords: []
  authors: []
site:
  title: 'test site'
  theme: article-theme
  nav: []
  actions:
    - title: Learn More
      url: https://mystmd.org/guide
  domains: []
```
in `myst.yml`. This **did not change the appearance at all** and `myst start -d` printed
```
'options' extra key ignored: theme (at /Users/juliusbusecke/Desktop/myst_test/myst.yml)
```
if I specify `template: article-theme` instead of `theme: article-theme` I get the expected change in output. 

Am I misunderstanding something between "theme" and "template" here or is this a bug in the docs?

> On a sidenote: It seems to me like I need to interrupt the server and run `myst start` again for any changes to have effect. This was not apparent to me at first glance. 

Happy to make a PR if someone can confirm that this is indeed a bug.
