### ISSUE TITLE
Inconsistent site build when an root file included a second time

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/mystmd#883]
If I have a `_toc.yml`:

```
format: jb-book
root: notebooks/nb-one
chapters:
  - title: Notebooks
    sections: 
      - file: notebooks/nb-one
      - file: notebooks/nb-two
```

and run `myst start`, my site appears as expected:

![image](https://github.com/executablebooks/mystmd/assets/1473646/4a78f2ba-5027-43cf-ab6d-1cf18e966e23)

If I then edit `nb-one.ipynb` and save it, the myst site rebuilds and the root/index page is updated to reflect the changes, but the changes are not shown on the other page. The other page shows a version prior to the last update.

![84dC4EbTcL](https://github.com/executablebooks/mystmd/assets/1473646/787b94c0-6ba4-4a4e-8856-f19081d21a47)
