### ISSUE TITLE
Support custom favicons

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystmd#925]
## Proposal

I'd like to be able to set a custom favicon. Based on [the website configuration docs](https://mystmd.org/guide/quickstart-myst-websites#configuration) I'd expect the configuration to look something like this:

```yaml
# See docs at: https://mystmd.org/guide/frontmatter
version: 1
project:
  # title:
  # description:
site:
  template: book-theme
  # title:
  # options:
  #   logo: my_logo.png
       favicon: my_favicon.png
```
