### ISSUE TITLE
Static build of trivial site produces invalid nav links

### ISSUE THREAD

**Issue by agoose77** [executablebooks/mystmd#950]
Building a trivial site from the following Markdown (duplicated into `test.md` and `test2.md`), the generated navigation points to `test2`, not `test2.html`. 

Content:
```markdown
# Test!
Hello world

````{note} Do better!

some minor comment that should show up with a smaller font
````
```

Config:
```yaml
# See docs at: https://mystmd.org/guide/frontmatter
version: 1
project:
  # title:
  # description:
  keywords: []
  authors: []
  github: https://github.com/executablebooks/mystmd
  # bibliography: []
site:
  template: book-theme
  # title:
  # options:
  #   logo: site_logo.png
  nav: []
  actions:
    - title: Learn More
      url: https://mystmd.org/guide
  domains: []

```

Build:
```bash
npx myst build --html
```

Is this intended?
