### ISSUE TITLE
🔢 Numbering options do not apply to proof/theorems/etc

### ISSUE THREAD

**Issue by fwkoch** [executablebooks/mystmd#952]
## Description

Numbering options can be customized in frontmatter for figures, headings, equations, even unknown kinds:
```
numberings:
  headings: true
  figure:
    template: Fig. %s
  unknown-kind: true
```

It should also work for [proofs/theorems/etc](https://mystmd.org/guide/proofs-and-theorems) but neither of these work; proof kinds are always numbered.
```
numberings:
  lemma: false
  prf:lemma: false
```

**Comment by fwkoch** [comment]
This _does_ apply correctly:
```yaml
numberings:
  proof:lemma:
    template: Lem. %s
```
but it is still not all the way there - you cannot disable numbering with
```yaml
numberings:
  proof:lemma: false
```
