### ISSUE TITLE
Cannot pip install editable

### ISSUE THREAD

**Issue by LecrisUT** [executablebooks/mystmd#975]
I am trying to get a simple editable install for tinkering with this project, but I can't seem to make it editably install the `mystmd-py` python project:
```console
$ pip install -e /path/to/mystmd/packages/mystmd-py
...
      OSError: Error getting the version from source `nodejs`: file does not exist: _package.json
      [end of output]
```
It seems that it would not work because even in the release workflow there are manual steps:
```yaml
      - name: Build Python package
        run: |
          pip install build
          # Copy over needed files
          cp ../mystmd/dist/myst.cjs src/mystmd_py/
          cp ../mystmd/package.json _package.json
          python -m build
        working-directory: packages/mystmd-py
```

Probably this is covered by
```console
$ npm install
$ npm run build
$ npm run dev
```
But I am not quire sure if that does the same thing. After running the `npm run dev`, can I edit in place the typescript files and then those are available to the `~/.local/bin/myst` executable?
