### ISSUE TITLE
LaTeX: `imports` not accessible to 

### ISSUE THREAD

**Issue by LecrisUT** [executablebooks/mystmd#978]
One would expect to be able to add to the list of package imports via
```yaml
exports:
  - format: pdf+tex
    imports:
      - physics
```
But this currently has no effect. Of course this is not complete since the imports could have additional options, but this should fix basic `\usepackage` needs

**Comment by LecrisUT** [comment]
There seems to be more nuance to this, because even if we include the missing `\usepackage`, `myst` will still complain of `Undefined control sequence:`

**Comment by jan-david-fischbach** [comment]
:+1: Any Progress on this?

**Comment by gl-yziquel** [comment]
I must say, it is not easy to find out of to get some \usepackage in mystmd working. I need `\reflectbox` from `\graphicx`, and struggling quite a bit finding the correct way to get that done.

**Comment by gl-yziquel** [comment]
@LecrisUT I've rebase your fix/978 branch and rebuilt the mystmd codebase on my machine. Could you please give me some guidance / advice as to how to use this `imports` field ?

**Comment by LecrisUT** [comment]
Iirc, you just need to add an `imports` field to the front-matter e.g.:
```yaml
exports:
  - format: pdf+tex
    imports:
      - physics
```

**Comment by gl-yziquel** [comment]
@LecrisUT Then, I'm doing something else wrong that I do not understand. Thank you, and sorry for disturbing you needlessly.

**Comment by gl-yziquel** [comment]
@LecrisUT Erratum: it in fact does work. I just checked it by importing the "cancel" package as follows:

```yaml
exports:
  - format: pdf+tex
    template: curvenote
    imports:
      - cancel
```

I am now able to write `\cancel{\exists}` with it, and could not before. So it indeed does work.

The `main` branch of my fork of `mystmd` contains the merge of current main branch and of your fix/978 branch.

https://github.com/gl-yziquel/mystmd

Please feel free to update your PR.
